#Run this script first to install all of the necessary packages!

#1. Install packages and load data-----
install.packages("tidyverse")
install.packages("lubridate")
install.packages("plyr")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("scales")
install.packages("RColorBrewer")
install.packages("shiny") 
install.packages("DT")
install.packages("shinythemes")
install.packages("lettercase")
install.packages("leaflet")
install.packages("stringr")
install.packages("sf")
install.packages("tidycensus")
install.packages("tigris")
install.packages("maps")
install.packages("plotly")
install.packages("rsconnect")
require(rgdal)


library("tidyverse")
library(plyr)
library(dplyr)
library(ggplot2)
library(scales)
library(RColorBrewer)
library(shiny) 
library("DT")
library("shinythemes")
library("lubridate")
library("lettercase")
library("leaflet")
library("stringr")
library("sf")
library("tidycensus")
library("tigris")
library("maps")
library("plotly")
library("rsconnect")
